/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.group404.y_2s_oop_project.views;

import com.group404.y_2s_oop_project.App;

/**
 *
 * @author D3MON
 */
public class layout_employeeMain extends javax.swing.JPanel {

    /**
     * Creates new form layout_employeeMain
     */
    public layout_employeeMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_myJobs = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        headerText = new javax.swing.JLabel();
        btn_orders = new javax.swing.JButton();
        btn_addSupplier = new javax.swing.JButton();
        btn_myJobs2 = new javax.swing.JButton();
        btn_addItemsToSuppleir = new javax.swing.JButton();

        btn_myJobs.setBackground(new java.awt.Color(153, 153, 0));
        btn_myJobs.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_myJobs.setForeground(new java.awt.Color(255, 255, 255));
        btn_myJobs.setText("ALLOCATED JOBS");
        btn_myJobs.setToolTipText("");
        btn_myJobs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_myJobsActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(731, 88));

        headerText.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        headerText.setForeground(new java.awt.Color(255, 255, 255));
        headerText.setText("ShipSharp Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerText)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
        );

        btn_orders.setBackground(new java.awt.Color(153, 153, 0));
        btn_orders.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_orders.setForeground(new java.awt.Color(255, 255, 255));
        btn_orders.setText("ORDERS");
        btn_orders.setToolTipText("");
        btn_orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordersActionPerformed(evt);
            }
        });

        btn_addSupplier.setBackground(new java.awt.Color(153, 153, 0));
        btn_addSupplier.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_addSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btn_addSupplier.setText("ADD SUPPLIER");
        btn_addSupplier.setToolTipText("");
        btn_addSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addSupplierActionPerformed(evt);
            }
        });

        btn_myJobs2.setBackground(new java.awt.Color(153, 153, 0));
        btn_myJobs2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_myJobs2.setForeground(new java.awt.Color(255, 255, 255));
        btn_myJobs2.setText("MANAGE SUPPLIERS");
        btn_myJobs2.setToolTipText("");
        btn_myJobs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_myJobs2ActionPerformed(evt);
            }
        });

        btn_addItemsToSuppleir.setBackground(new java.awt.Color(153, 153, 0));
        btn_addItemsToSuppleir.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_addItemsToSuppleir.setForeground(new java.awt.Color(255, 255, 255));
        btn_addItemsToSuppleir.setText("ALLOCATE ITEMS TO SUPPLIERS");
        btn_addItemsToSuppleir.setToolTipText("");
        btn_addItemsToSuppleir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addItemsToSuppleirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_orders, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_myJobs, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_myJobs2)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_addItemsToSuppleir, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_orders)
                    .addComponent(btn_myJobs)
                    .addComponent(btn_myJobs2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_addSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_addItemsToSuppleir)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_myJobsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_myJobsActionPerformed
        App.openLayout("layout_employeeMyJobs", "My Allocated Jobs");
    }//GEN-LAST:event_btn_myJobsActionPerformed

    private void btn_ordersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordersActionPerformed
        App.openLayout("layout_employeeOrders", "Order Spare Parts");
    }//GEN-LAST:event_btn_ordersActionPerformed

    private void btn_addSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addSupplierActionPerformed
        App.openLayout("layout_employeeAddSupplier", "Add Supplier");
    }//GEN-LAST:event_btn_addSupplierActionPerformed

    private void btn_myJobs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_myJobs2ActionPerformed
        App.openLayout("layout_employeeSupplierList", "Supplier List");
    }//GEN-LAST:event_btn_myJobs2ActionPerformed

    private void btn_addItemsToSuppleirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addItemsToSuppleirActionPerformed
        App.openLayout("layout_employeeAddItemsToSupplier", "Allocate Items To Supplier");
    }//GEN-LAST:event_btn_addItemsToSuppleirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addItemsToSuppleir;
    private javax.swing.JButton btn_addSupplier;
    private javax.swing.JButton btn_myJobs;
    private javax.swing.JButton btn_myJobs2;
    private javax.swing.JButton btn_orders;
    private javax.swing.JLabel headerText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
